<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use App\Models\Classes;


class ClassesSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $classes = [
            // CS
            // CP352001 Data Structure
            [
                'section_num' => 1,
                'title' => 'กลุ่ม 1',
                'open_num' => 42,
                'enrolled_num' => 42,
                'available_num' => 0,
                'teachers_id' => 24,
                'courses_id' => 1,
                'semesters_id' => 3,
                'major_id' => 1,
            ],
            [
                'section_num' => 2,
                'title' => 'กลุ่ม 2',
                'open_num' => 40,
                'enrolled_num' => 37,
                'available_num' => 3,
                'teachers_id' => 24,
                'courses_id' => 1,
                'semesters_id' => 3,
                'major_id' => 1,
            ],
            [
                'section_num' => 3,
                'title' => 'กลุ่ม 3',
                'open_num' => 40,
                'enrolled_num' => 34,
                'available_num' => 6,
                'teachers_id' => 24,
                'courses_id' => 16,
                'semesters_id' => 3,
                'major_id' => 2,
            ],
            [
                'section_num' => 4,
                'title' => 'กลุ่ม 4',
                'open_num' => 40,
                'enrolled_num' => 31,
                'available_num' => 9,
                'teachers_id' => 24,
                'courses_id' => 16,
                'semesters_id' => 3,
                'major_id' => 2,
            ],
            // CP352002 User Experience Design
            [
                'section_num' => 1,
                'title' => 'กลุ่ม 1',
                'open_num' => 45,
                'enrolled_num' => 44,
                'available_num' => 1,
                'teachers_id' => 12,
                'courses_id' => 2,
                'semesters_id' => 3,
                'major_id' => 1,
            ],
            [
                'section_num' => 2,
                'title' => 'กลุ่ม 2',
                'open_num' => 43,
                'enrolled_num' => 35,
                'available_num' => 8,
                'teachers_id' => 12,
                'courses_id' => 2,
                'semesters_id' => 3,
                'major_id' => 1,
            ],
            [
                'section_num' => 3,
                'title' => 'กลุ่ม 3',
                'open_num' => 38,
                'enrolled_num' => 37,
                'available_num' => 1,
                'teachers_id' => 12,
                'courses_id' => 17,
                'semesters_id' => 3,
                'major_id' => 2,
            ],
            [
                'section_num' => 4,
                'title' => 'กลุ่ม 4',
                'open_num' => 37,
                'enrolled_num' => 27,
                'available_num' => 10,
                'teachers_id' => 12,
                'courses_id' => 17,
                'semesters_id' => 3,
                'major_id' => 2,
            ],
            // CP351203 Web Programming and Application
            [
                'section_num' => 1,
                'title' => 'กลุ่ม 1',
                'open_num' => 22,
                'enrolled_num' => 22,
                'available_num' => 0,
                'teachers_id' => 30,
                'courses_id' => 3,
                'semesters_id' => 3,
                'major_id' => 1,
            ],
            [
                'section_num' => 2,
                'title' => 'กลุ่ม 2',
                'open_num' => 26,
                'enrolled_num' => 26,
                'available_num' => 0,
                'teachers_id' => 30,
                'courses_id' => 18,
                'semesters_id' => 3,
                'major_id' => 2,
            ],

            // CP353001 Operating Systems and System Calls Programming
            [
                'section_num' => 1,
                'title' => 'กลุ่ม 1',
                'open_num' => 38,
                'enrolled_num' => 37,
                'available_num' => 1,
                'teachers_id' => 15,
                'courses_id' => 4,
                'semesters_id' => 3,
                'major_id' => 1,
            ],
            [
                'section_num' => 2,
                'title' => 'กลุ่ม 2',
                'open_num' => 38,
                'enrolled_num' => 37,
                'available_num' => 1,
                'teachers_id' => 15,
                'courses_id' => 4,
                'semesters_id' => 3,
                'major_id' => 1,
            ],
            [
                'section_num' => 3,
                'title' => 'กลุ่ม 3',
                'open_num' => 33,
                'enrolled_num' => 23,
                'available_num' => 10,
                'teachers_id' => 15,
                'courses_id' => 19,
                'semesters_id' => 3,
                'major_id' => 2,
            ],
            [
                'section_num' => 4,
                'title' => 'กลุ่ม 4',
                'open_num' => 36,
                'enrolled_num' => 36,
                'available_num' => 0,
                'teachers_id' => 15,
                'courses_id' => 19,
                'semesters_id' => 3,
                'major_id' => 2,
            ],

            // CP351001 Fundamental Computer Science
            [
                'section_num' => 1,
                'title' => 'กลุ่ม 1',
                'open_num' => 51,
                'enrolled_num' => 49,
                'available_num' => 2,
                'teachers_id' => 16,
                'courses_id' => 5,
                'semesters_id' => 3,
                'major_id' => 1,
            ],
            [
                'section_num' => 2,
                'title' => 'กลุ่ม 2',
                'open_num' => 51,
                'enrolled_num' => 51,
                'available_num' => 0,
                'teachers_id' => 16,
                'courses_id' => 5,
                'semesters_id' => 3,
                'major_id' => 1,
            ],
            [
                'section_num' => 3,
                'title' => 'กลุ่ม 3',
                'open_num' => 45,
                'enrolled_num' => 45,
                'available_num' => 0,
                'teachers_id' => 16,
                'courses_id' => 20,
                'semesters_id' => 3,
                'major_id' => 2,
            ],
            [
                'section_num' => 4,
                'title' => 'กลุ่ม 4',
                'open_num' => 45,
                'enrolled_num' => 45,
                'available_num' => 0,
                'teachers_id' => 16,
                'courses_id' => 20,
                'semesters_id' => 3,
                'major_id' => 2,
            ],

            // CP353201 Software Quality Assurance
            [
                'section_num' => 1,
                'title' => 'กลุ่ม 1',
                'open_num' => 35,
                'enrolled_num' => 24,
                'available_num' => 11,
                'teachers_id' => 4,
                'courses_id' => 6,
                'semesters_id' => 3,
                'major_id' => 1,
            ],
            [
                'section_num' => 2,
                'title' => 'กลุ่ม 2',
                'open_num' => 35,
                'enrolled_num' => 3,
                'available_num' => 32,
                'teachers_id' => 4,
                'courses_id' => 21,
                'semesters_id' => 3,
                'major_id' => 2,
            ],

            // CP353108 Neural Network and Deep Learning
            [
                'section_num' => 1,
                'title' => 'กลุ่ม 1',
                'open_num' => 25,
                'enrolled_num' => 25,
                'available_num' => 0,
                'teachers_id' => 37,
                'courses_id' => 7,
                'semesters_id' => 3,
                'major_id' => 1,
            ],
            [
                'section_num' => 2,
                'title' => 'กลุ่ม 2',
                'open_num' => 25,
                'enrolled_num' => 19,
                'available_num' => 6,
                'teachers_id' => 37,
                'courses_id' => 22,
                'semesters_id' => 3,
                'major_id' => 2,
            ],

            // CP353003 Artificial Intelligence
            [
                'section_num' => 1,
                'title' => 'กลุ่ม 1',
                'open_num' => 40,
                'enrolled_num' => 38,
                'available_num' => 2,
                'teachers_id' => 26,
                'courses_id' => 8,
                'semesters_id' => 3,
                'major_id' => 1,
            ],
            [
                'section_num' => 2,
                'title' => 'กลุ่ม 2',
                'open_num' => 38,
                'enrolled_num' => 36,
                'available_num' => 2,
                'teachers_id' => 26,
                'courses_id' => 8,
                'semesters_id' => 3,
                'major_id' => 1,
            ],
            [
                'section_num' => 3,
                'title' => 'กลุ่ม 3',
                'open_num' => 66,
                'enrolled_num' => 62,
                'available_num' => 4,
                'teachers_id' => 26,
                'courses_id' => 23,
                'semesters_id' => 3,
                'major_id' => 2,
            ],

            // CP353102 Introduction to Machine Learning
            [
                'section_num' => 1,
                'title' => 'กลุ่ม 1',
                'open_num' => 26,
                'enrolled_num' => 26,
                'available_num' => 0,
                'teachers_id' => 36,
                'courses_id' => 9,
                'semesters_id' => 3,
                'major_id' => 1,
            ],
            [
                'section_num' => 2,
                'title' => 'กลุ่ม 2',
                'open_num' => 25,
                'enrolled_num' => 21,
                'available_num' => 4,
                'teachers_id' => 36,
                'courses_id' => 24,
                'semesters_id' => 3,
                'major_id' => 2,
            ],

            // CP353103 Data Analytics and Application
            [
                'section_num' => 1,
                'title' => 'กลุ่ม 1',
                'open_num' => 35,
                'enrolled_num' => 16,
                'available_num' => 19,
                'teachers_id' => 8,
                'courses_id' => 10,
                'semesters_id' => 3,
                'major_id' => 1,
            ],
            [
                'section_num' => 2,
                'title' => 'กลุ่ม 2',
                'open_num' => 35,
                'enrolled_num' => 32,
                'available_num' => 3,
                'teachers_id' => 8,
                'courses_id' => 25,
                'semesters_id' => 3,
                'major_id' => 2,
            ],

            // CP352201 Web Design Technologies
            [
                'section_num' => 1,
                'title' => 'กลุ่ม 1',
                'open_num' => 30,
                'enrolled_num' => 2,
                'available_num' => 28,
                'teachers_id' => 21,
                'courses_id' => 11,
                'semesters_id' => 3,
                'major_id' => 1,
            ],
            [
                'section_num' => 2,
                'title' => 'กลุ่ม 2',
                'open_num' => 35,
                'enrolled_num' => 16,
                'available_num' => 19,
                'teachers_id' => 21,
                'courses_id' => 26,
                'semesters_id' => 3,
                'major_id' => 2,
            ],

            // CP351002 Structure Programming Languages for Computer Science
            [
                'section_num' => 1,
                'title' => 'กลุ่ม 1',
                'open_num' => 51,
                'enrolled_num' => 50,
                'available_num' => 1,
                'teachers_id' => 3,
                'courses_id' => 12,
                'semesters_id' => 3,
                'major_id' => 1,
            ],
            [
                'section_num' => 2,
                'title' => 'กลุ่ม 2',
                'open_num' => 51,
                'enrolled_num' => 50,
                'available_num' => 1,
                'teachers_id' => 3,
                'courses_id' => 12,
                'semesters_id' => 3,
                'major_id' => 1,
            ],
            [
                'section_num' => 3,
                'title' => 'กลุ่ม 3',
                'open_num' => 45,
                'enrolled_num' => 45,
                'available_num' => 0,
                'teachers_id' => 3,
                'courses_id' => 27,
                'semesters_id' => 3,
                'major_id' => 2,
            ],
            [
                'section_num' => 4,
                'title' => 'กลุ่ม 4',
                'open_num' => 45,
                'enrolled_num' => 44,
                'available_num' => 1,
                'teachers_id' => 3,
                'courses_id' => 27,
                'semesters_id' => 3,
                'major_id' => 2,
            ],

            // CP353761 Seminar in Computer Science
            [
                'section_num' => 1,
                'title' => 'กลุ่ม 1',
                'open_num' => 80,
                'enrolled_num' => 74,
                'available_num' => 6,
                'teachers_id' => 3,
                'courses_id' => 13,
                'semesters_id' => 3,
                'major_id' => 1,
            ],
            [
                'section_num' => 2,
                'title' => 'กลุ่ม 2',
                'open_num' => 70,
                'enrolled_num' => 61,
                'available_num' => 9,
                'teachers_id' => 3,
                'courses_id' => 28,
                'semesters_id' => 3,
                'major_id' => 2,
            ],

            // CP353002 Principles of Software Design and Development
            [
                'section_num' => 1,
                'title' => 'กลุ่ม 1',
                'open_num' => 40,
                'enrolled_num' => 40,
                'available_num' => 0,
                'teachers_id' => 10,
                'courses_id' => 14,
                'semesters_id' => 3,
                'major_id' => 1,
            ],
            [
                'section_num' => 2,
                'title' => 'กลุ่ม 2',
                'open_num' => 38,
                'enrolled_num' => 34,
                'available_num' => 4,
                'teachers_id' => 10,
                'courses_id' => 14,
                'semesters_id' => 3,
                'major_id' => 1,
            ],
            [
                'section_num' => 3,
                'title' => 'กลุ่ม 3',
                'open_num' => 41,
                'enrolled_num' => 39,
                'available_num' => 1,
                'teachers_id' => 10,
                'courses_id' => 29,
                'semesters_id' => 3,
                'major_id' => 2,
            ],
            [
                'section_num' => 4,
                'title' => 'กลุ่ม 4',
                'open_num' => 33,
                'enrolled_num' => 24,
                'available_num' => 9,
                'teachers_id' => 10,
                'courses_id' => 29,
                'semesters_id' => 3,
                'major_id' => 2,
            ],

            // SC313002 Principles of Software Design and Development
            [
                'section_num' => 1,
                'title' => 'กลุ่ม 1',
                'open_num' => 5,
                'enrolled_num' => 3,
                'available_num' => 2,
                'teachers_id' => 10,
                'courses_id' => 15,
                'semesters_id' => 3,
                'major_id' => 1,
            ],
            [
                'section_num' => 2,
                'title' => 'กลุ่ม 2',
                'open_num' => 5,
                'enrolled_num' => 1,
                'available_num' => 4,
                'teachers_id' => 10,
                'courses_id' => 30,
                'semesters_id' => 3,
                'major_id' => 2,
            ],
            // IT
            // SC361002 Structured Programming for Information Technology
            [
                'section_num' => 1,
                'title' => 'กลุ่ม 1',
                'open_num' => 44,
                'enrolled_num' => 43,
                'available_num' => 1,
                'teachers_id' => 30,
                'courses_id' => 31,
                'semesters_id' => 3,
                'major_id' => 3,
            ],
            [
                'section_num' => 2,
                'title' => 'กลุ่ม 2',
                'open_num' => 43,
                'enrolled_num' => 43,
                'available_num' => 0,
                'teachers_id' => 30,
                'courses_id' => 31,
                'semesters_id' => 3,
                'major_id' => 3,
            ],
            [
                'section_num' => 3,
                'title' => 'กลุ่ม 3',
                'open_num' => 10,
                'enrolled_num' => 8,
                'available_num' => 2,
                'teachers_id' => 30,
                'courses_id' => 49,
                'semesters_id' => 3,
                'major_id' => 4,
            ],

            // SC362004 Web Application Programming
            [
                'section_num' => 1,
                'title' => 'กลุ่ม 1',
                'open_num' => 38,
                'enrolled_num' => 38,
                'available_num' => 0,
                'teachers_id' => 30,
                'courses_id' => 32,
                'semesters_id' => 3,
                'major_id' => 3,
            ],
            [
                'section_num' => 2,
                'title' => 'กลุ่ม 2',
                'open_num' => 38,
                'enrolled_num' => 33,
                'available_num' => 5,
                'teachers_id' => 30,
                'courses_id' => 32,
                'semesters_id' => 3,
                'major_id' => 3,
            ],
            [
                'section_num' => 3,
                'title' => 'กลุ่ม 3',
                'open_num' => 50,
                'enrolled_num' => 34,
                'available_num' => 16,
                'teachers_id' => 30,
                'courses_id' => 50,
                'semesters_id' => 3,
                'major_id' => 4,
            ],
            [
                'section_num' => 4,
                'title' => 'กลุ่ม 4',
                'open_num' => 1,
                'enrolled_num' => 1,
                'available_num' => 0,
                'teachers_id' => 30,
                'courses_id' => 50,
                'semesters_id' => 3,
                'major_id' => 4,
            ],

            // SC363762 Research Methodology
            [
                'section_num' => 1,
                'title' => 'กลุ่ม 1',
                'open_num' => 90,
                'enrolled_num' => 60,
                'available_num' => 30,
                'teachers_id' => 30,
                'courses_id' => 33,
                'semesters_id' => 3,
                'major_id' => 3,
            ],
            [
                'section_num' => 2,
                'title' => 'กลุ่ม 2',
                'open_num' => 50,
                'enrolled_num' => 34,
                'available_num' => 16,
                'teachers_id' => 30,
                'courses_id' => 51,
                'semesters_id' => 3,
                'major_id' => 4,
            ],

            // SC362003 Introduction to Computer Networking
            [
                'section_num' => 1,
                'title' => 'กลุ่ม 1',
                'open_num' => 38,
                'enrolled_num' => 37,
                'available_num' => 1,
                'teachers_id' => 9,
                'courses_id' => 34,
                'semesters_id' => 3,
                'major_id' => 3,
            ],
            [
                'section_num' => 2,
                'title' => 'กลุ่ม 2',
                'open_num' => 38,
                'enrolled_num' => 32,
                'available_num' => 6,
                'teachers_id' => 9,
                'courses_id' => 34,
                'semesters_id' => 3,
                'major_id' => 3,
            ],
            [
                'section_num' => 3,
                'title' => 'กลุ่ม 3',
                'open_num' => 0,
                'enrolled_num' => 0,
                'available_num' => 0,
                'teachers_id' => 9,
                'courses_id' => 52,
                'semesters_id' => 3,
                'major_id' => 4,
            ],
            [
                'section_num' => 4,
                'title' => 'กลุ่ม 4',
                'open_num' => 40,
                'enrolled_num' => 39,
                'available_num' => 1,
                'teachers_id' => 9,
                'courses_id' => 52,
                'semesters_id' => 3,
                'major_id' => 4,
            ],

            // 342222 Introduction to Computer Networking
            [
                'section_num' => 1,
                'title' => 'กลุ่ม 1',
                'open_num' => 5,
                'enrolled_num' => 1,
                'available_num' => 4,
                'teachers_id' => 9,
                'courses_id' => 35,
                'semesters_id' => 3,
                'major_id' => 3,
            ],
            [
                'section_num' => 2,
                'title' => 'กลุ่ม 2',
                'open_num' => 5,
                'enrolled_num' => 0,
                'available_num' => 5,
                'teachers_id' => 9,
                'courses_id' => 53,
                'semesters_id' => 3,
                'major_id' => 4,
            ],

            // SC362005 Database Analysis and Design
            [
                'section_num' => 1,
                'title' => 'กลุ่ม 1',
                'open_num' => 38,
                'enrolled_num' => 35,
                'available_num' => 3,
                'teachers_id' => 25,
                'courses_id' => 36,
                'semesters_id' => 3,
                'major_id' => 3,
            ],
            [
                'section_num' => 2,
                'title' => 'กลุ่ม 2',
                'open_num' => 38,
                'enrolled_num' => 36,
                'available_num' => 2,
                'teachers_id' => 25,
                'courses_id' => 36,
                'semesters_id' => 3,
                'major_id' => 3,
            ],
            [
                'section_num' => 3,
                'title' => 'กลุ่ม 3',
                'open_num' => 38,
                'enrolled_num' => 30,
                'available_num' => 8,
                'teachers_id' => 25,
                'courses_id' => 54,
                'semesters_id' => 3,
                'major_id' => 4,
            ],
            [
                'section_num' => 4,
                'title' => 'กลุ่ม 4',
                'open_num' => 38,
                'enrolled_num' => 28,
                'available_num' => 10,
                'teachers_id' => 25,
                'courses_id' => 54,
                'semesters_id' => 3,
                'major_id' => 4,
            ],
            // SC363101 Software Testing and Quality Assurance
            [
                'section_num' => 1,
                'title' => 'กลุ่ม 1',
                'open_num' => 42,
                'enrolled_num' => 38,
                'available_num' => 4,
                'teachers_id' => 14,
                'courses_id' => 37,
                'semesters_id' => 3,
                'major_id' => 3,
            ],
            [
                'section_num' => 2,
                'title' => 'กลุ่ม 2',
                'open_num' => 30,
                'enrolled_num' => 20,
                'available_num' => 10,
                'teachers_id' => 14,
                'courses_id' => 55,
                'semesters_id' => 3,
                'major_id' => 4,
            ],

            // SC363002 Strategic Management of Information Technology
            [
                'section_num' => 1,
                'title' => 'กลุ่ม 1',
                'open_num' => 60,
                'enrolled_num' => 53,
                'available_num' => 7,
                'teachers_id' => 23,
                'courses_id' => 38,
                'semesters_id' => 3,
                'major_id' => 3,
            ],
            [
                'section_num' => 2,
                'title' => 'กลุ่ม 2',
                'open_num' => 45,
                'enrolled_num' => 35,
                'available_num' => 10,
                'teachers_id' => 23,
                'courses_id' => 56,
                'semesters_id' => 3,
                'major_id' => 4,
            ],
            // SC363102 Business Intelligence System
            [
                'section_num' => 1,
                'title' => 'กลุ่ม 1',
                'open_num' => 20,
                'enrolled_num' => 13,
                'available_num' => 7,
                'teachers_id' => 23,
                'courses_id' => 39,
                'semesters_id' => 3,
                'major_id' => 3,
            ],
            [
                'section_num' => 2,
                'title' => 'กลุ่ม 2',
                'open_num' => 20,
                'enrolled_num' => 12,
                'available_num' => 8,
                'teachers_id' => 23,
                'courses_id' => 57,
                'semesters_id' => 3,
                'major_id' => 4,
            ],
            // SC362102 Software Engineering
            [
                'section_num' => 1,
                'title' => 'กลุ่ม 1',
                'open_num' => 32,
                'enrolled_num' => 31,
                'available_num' => 1,
                'teachers_id' => 31,
                'courses_id' => 40,
                'semesters_id' => 3,
                'major_id' => 3,
            ],
            [
                'section_num' => 2,
                'title' => 'กลุ่ม 2',
                'open_num' => 30,
                'enrolled_num' => 21,
                'available_num' => 9,
                'teachers_id' => 31,
                'courses_id' => 58,
                'semesters_id' => 3,
                'major_id' => 4,
            ],
            // SC363001 Systems Analysis and Design
            [
                'section_num' => 1,
                'title' => 'กลุ่ม 1',
                'open_num' => 60,
                'enrolled_num' => 55,
                'available_num' => 5,
                'teachers_id' => 31,
                'courses_id' => 41,
                'semesters_id' => 3,
                'major_id' => 3,
            ],
            [
                'section_num' => 2,
                'title' => 'กลุ่ม 2',
                'open_num' => 35,
                'enrolled_num' => 34,
                'available_num' => 1,
                'teachers_id' => 31,
                'courses_id' => 59,
                'semesters_id' => 3,
                'major_id' => 4,
            ],
            // SC361001 Inspiration in IT Career
            [
                'section_num' => 1,
                'title' => 'กลุ่ม 1',
                'open_num' => 90,
                'enrolled_num' => 86,
                'available_num' => 4,
                'teachers_id' => 14,
                'courses_id' => 42,
                'semesters_id' => 3,
                'major_id' => 3,
            ],

            // SC362001 Operating Systems
            [
                'section_num' => 1,
                'title' => 'กลุ่ม 1',
                'open_num' => 38,
                'enrolled_num' => 37,
                'available_num' => 1,
                'teachers_id' => 15,
                'courses_id' => 43,
                'semesters_id' => 3,
                'major_id' => 3,
            ],
            [
                'section_num' => 2,
                'title' => 'กลุ่ม 2',
                'open_num' => 38,
                'enrolled_num' => 34,
                'available_num' => 4,
                'teachers_id' => 15,
                'courses_id' => 43,
                'semesters_id' => 3,
                'major_id' => 3,
            ],
            [
                'section_num' => 3,
                'title' => 'กลุ่ม 3',
                'open_num' => 38,
                'enrolled_num' => 36,
                'available_num' => 2,
                'teachers_id' => 15,
                'courses_id' => 61,
                'semesters_id' => 3,
                'major_id' => 4,
            ],
            [
                'section_num' => 4,
                'title' => 'กลุ่ม 4',
                'open_num' => 38,
                'enrolled_num' => 12,
                'available_num' => 26,
                'teachers_id' => 15,
                'courses_id' => 61,
                'semesters_id' => 3,
                'major_id' => 4,
            ],

            // CP363205 Data Serialization Languages and Applications
            [
                'section_num' => 1,
                'title' => 'กลุ่ม 1',
                'open_num' => 55,
                'enrolled_num' => 48,
                'available_num' => 7,
                'teachers_id' => 11,
                'courses_id' => 44,
                'semesters_id' => 3,
                'major_id' => 3,
            ],
            [
                'section_num' => 2,
                'title' => 'กลุ่ม 2',
                'open_num' => 55,
                'enrolled_num' => 52,
                'available_num' => 3,
                'teachers_id' => 11,
                'courses_id' => 62,
                'semesters_id' => 3,
                'major_id' => 4,
            ],
            // SC320001 Introduction To Information And Communication Technology
            [
                'section_num' => 1,
                'title' => 'กลุ่ม 1',
                'open_num' => 120,
                'enrolled_num' => 85,
                'available_num' => 35,
                'teachers_id' => 32,
                'courses_id' => 45,
                'semesters_id' => 3,
                'major_id' => 3,
            ],
            // SC362201 Web Design Technologies
            [
                'section_num' => 1,
                'title' => 'กลุ่ม 1',
                'open_num' => 30,
                'enrolled_num' => 26,
                'available_num' => 4,
                'teachers_id' => 21,
                'courses_id' => 46,
                'semesters_id' => 3,
                'major_id' => 3,
            ],
            [
                'section_num' => 2,
                'title' => 'กลุ่ม 2',
                'open_num' => 30,
                'enrolled_num' => 23,
                'available_num' => 7,
                'teachers_id' => 21,
                'courses_id' => 64,
                'semesters_id' => 3,
                'major_id' => 4,
            ],
            // SC362301 Digital Logic and Embedded Systems
            [
                'section_num' => 1,
                'title' => 'กลุ่ม 1',
                'open_num' => 30,
                'enrolled_num' => 24,
                'available_num' => 6,
                'teachers_id' => 22,
                'courses_id' => 47,
                'semesters_id' => 3,
                'major_id' => 3,
            ],
            [
                'section_num' => 2,
                'title' => 'กลุ่ม 2',
                'open_num' => 30,
                'enrolled_num' => 24,
                'available_num' => 6,
                'teachers_id' => 22,
                'courses_id' => 65,
                'semesters_id' => 3,
                'major_id' => 4,
            ],
            // SC363003 Information Technology Profession
            [
                'section_num' => 1,
                'title' => 'กลุ่ม 1',
                'open_num' => 90,
                'enrolled_num' => 55,
                'available_num' => 25,
                'teachers_id' => 22,
                'courses_id' => 48,
                'semesters_id' => 3,
                'major_id' => 3,
            ],
            [
                'section_num' => 2,
                'title' => 'กลุ่ม 2',
                'open_num' => 50,
                'enrolled_num' => 38,
                'available_num' => 12,
                'teachers_id' => 22,
                'courses_id' => 66,
                'semesters_id' => 3,
                'major_id' => 4,
            ],
            // GIS
            // CP350002 Data Structure
            [
                'section_num' => 1,
                'title' => 'กลุ่ม 1',
                'open_num' => 75,
                'enrolled_num' => 65,
                'available_num' => 10,
                'teachers_id' => 12,
                'courses_id' => 67,
                'semesters_id' => 3,
                'major_id' => 5,
            ],
            [
                'section_num' => 2,
                'title' => 'กลุ่ม 2',
                'open_num' => 45,
                'enrolled_num' => 31,
                'available_num' => 14,
                'teachers_id' => 12,
                'courses_id' => 73,
                'semesters_id' => 3,
                'major_id' => 6,
            ],
            // CP371031 Basics of Information Technology
            [
                'section_num' => 1,
                'title' => 'กลุ่ม 1',
                'open_num' => 42,
                'enrolled_num' => 42,
                'available_num' => 0,
                'teachers_id' => 2,
                'courses_id' => 68,
                'semesters_id' => 3,
                'major_id' => 5,
            ],
            [
                'section_num' => 2,
                'title' => 'กลุ่ม 2',
                'open_num' => 40,
                'enrolled_num' => 35,
                'available_num' => 5,
                'teachers_id' => 2,
                'courses_id' => 68,
                'semesters_id' => 3,
                'major_id' => 5,
            ],
            [
                'section_num' => 3,
                'title' => 'กลุ่ม 3',
                'open_num' => 5,
                'enrolled_num' => 2,
                'available_num' => 3,
                'teachers_id' => 2,
                'courses_id' => 74,
                'semesters_id' => 3,
                'major_id' => 6,
            ],

            // CP372002 Introduction to Geographic Information System
            [
                'section_num' => 1,
                'title' => 'กลุ่ม 1',
                'open_num' => 69,
                'enrolled_num' => 65,
                'available_num' => 4,
                'teachers_id' => 6,
                'courses_id' => 69,
                'semesters_id' => 3,
                'major_id' => 5,
            ],
            [
                'section_num' => 2,
                'title' => 'กลุ่ม 2',
                'open_num' => 40,
                'enrolled_num' => 32,
                'available_num' => 8,
                'teachers_id' => 6,
                'courses_id' => 75,
                'semesters_id' => 3,
                'major_id' => 6,
            ],
            // CP372011 Fundamentals of Remote Sensing
            [
                'section_num' => 1,
                'title' => 'กลุ่ม 1',
                'open_num' => 65,
                'enrolled_num' => 65,
                'available_num' => 0,
                'teachers_id' => 20,
                'courses_id' => 70,
                'semesters_id' => 3,
                'major_id' => 5,
            ],
            [
                'section_num' => 2,
                'title' => 'กลุ่ม 2',
                'open_num' => 40,
                'enrolled_num' => 32,
                'available_num' => 8,
                'teachers_id' => 20,
                'courses_id' => 76,
                'semesters_id' => 3,
                'major_id' => 6,
            ],
            // CP373232 Spatial Database Management
            [
                'section_num' => 1,
                'title' => 'กลุ่ม 1',
                'open_num' => 49,
                'enrolled_num' => 46,
                'available_num' => 3,
                'teachers_id' => 2,
                'courses_id' => 71,
                'semesters_id' => 3,
                'major_id' => 5,
            ],
            [
                'section_num' => 2,
                'title' => 'กลุ่ม 2',
                'open_num' => 10,
                'enrolled_num' => 6,
                'available_num' => 4,
                'teachers_id' => 2,
                'courses_id' => 77,
                'semesters_id' => 3,
                'major_id' => 6,
            ],
            // CP373112 Unmanned Aerial Vehicle Mapping
            [
                'section_num' => 1,
                'title' => 'กลุ่ม 1',
                'open_num' => 75,
                'enrolled_num' => 68,
                'available_num' => 7,
                'teachers_id' => 6,
                'courses_id' => 72,
                'semesters_id' => 3,
                'major_id' => 5,
            ],
            [
                'section_num' => 2,
                'title' => 'กลุ่ม 2',
                'open_num' => 25,
                'enrolled_num' => 20,
                'available_num' => 5,
                'teachers_id' => 6,
                'courses_id' => 78,
                'semesters_id' => 3,
                'major_id' => 6,
            ],
            // AI
            // CP411106 Programming for Machine Learning
            [
                'section_num' => 1,
                'title' => 'กลุ่ม 1',
                'open_num' => 43,
                'enrolled_num' => 43,
                'available_num' => 0,
                'teachers_id' => 29,
                'courses_id' => 79,
                'semesters_id' => 3,
                'major_id' => 7,
            ],
            [
                'section_num' => 2,
                'title' => 'กลุ่ม 2',
                'open_num' => 42,
                'enrolled_num' => 42,
                'available_num' => 0,
                'teachers_id' => 29,
                'courses_id' => 79,
                'semesters_id' => 3,
                'major_id' => 7,
            ],
            [
                'section_num' => 3,
                'title' => 'กลุ่ม 3',
                'open_num' => 60,
                'enrolled_num' => 58,
                'available_num' => 2,
                'teachers_id' => 29,
                'courses_id' => 86,
                'semesters_id' => 3,
                'major_id' => 8,
            ],
            // CP411701 Artificial Intelligence Inspiration
            [
                'section_num' => 1,
                'title' => 'กลุ่ม 1',
                'open_num' => 85,
                'enrolled_num' => 85,
                'available_num' => 0,
                'teachers_id' => 26,
                'courses_id' => 80,
                'semesters_id' => 3,
                'major_id' => 7,
            ],
            [
                'section_num' => 2,
                'title' => 'กลุ่ม 2',
                'open_num' => 60,
                'enrolled_num' => 58,
                'available_num' => 2,
                'teachers_id' => 26,
                'courses_id' => 87,
                'semesters_id' => 3,
                'major_id' => 8,
            ],
            // CP412703 Artificial Intelligence Workshop I
            [
                'section_num' => 1,
                'title' => 'กลุ่ม 1',
                'open_num' => 47,
                'enrolled_num' => 40,
                'available_num' => 7,
                'teachers_id' => 26,
                'courses_id' => 81,
                'semesters_id' => 3,
                'major_id' => 7,
            ],
            [
                'section_num' => 2,
                'title' => 'กลุ่ม 2',
                'open_num' => 48,
                'enrolled_num' => 46,
                'available_num' => 2,
                'teachers_id' => 26,
                'courses_id' => 88,
                'semesters_id' => 3,
                'major_id' => 8,
            ],
            // CP412002 Machine Learning
            [
                'section_num' => 1,
                'title' => 'กลุ่ม 1',
                'open_num' => 47,
                'enrolled_num' => 39,
                'available_num' => 8,
                'teachers_id' => 36,
                'courses_id' => 82,
                'semesters_id' => 3,
                'major_id' => 7,
            ],
            [
                'section_num' => 2,
                'title' => 'กลุ่ม 2',
                'open_num' => 47,
                'enrolled_num' => 46,
                'available_num' => 1,
                'teachers_id' => 36,
                'courses_id' => 89,
                'semesters_id' => 3,
                'major_id' => 8,
            ],
            // CP412003 Data Science
            [
                'section_num' => 1,
                'title' => 'กลุ่ม 1',
                'open_num' => 47,
                'enrolled_num' => 40,
                'available_num' => 7,
                'teachers_id' => 37,
                'courses_id' => 83,
                'semesters_id' => 3,
                'major_id' => 7,
            ],
            [
                'section_num' => 2,
                'title' => 'กลุ่ม 2',
                'open_num' => 47,
                'enrolled_num' => 46,
                'available_num' => 1,
                'teachers_id' => 37,
                'courses_id' => 90,
                'semesters_id' => 3,
                'major_id' => 8,
            ],
            // CP412004 Neural Network and Deep Learning
            [
                'section_num' => 1,
                'title' => 'กลุ่ม 1',
                'open_num' => 47,
                'enrolled_num' => 45,
                'available_num' => 2,
                'teachers_id' => 37,
                'courses_id' => 84,
                'semesters_id' => 3,
                'major_id' => 7,
            ],
            [
                'section_num' => 2,
                'title' => 'กลุ่ม 2',
                'open_num' => 47,
                'enrolled_num' => 40,
                'available_num' => 7,
                'teachers_id' => 37,
                'courses_id' => 91,
                'semesters_id' => 3,
                'major_id' => 8,
            ],
            // CP411107 Data Structures and Algorithms
            [
                'section_num' => 1,
                'title' => 'กลุ่ม 1',
                'open_num' => 47,
                'enrolled_num' => 30,
                'available_num' => 7,
                'teachers_id' => 22,
                'courses_id' => 85,
                'semesters_id' => 3,
                'major_id' => 7,
            ],
            [
                'section_num' => 2,
                'title' => 'กลุ่ม 2',
                'open_num' => 47,
                'enrolled_num' => 46,
                'available_num' => 1,
                'teachers_id' => 22,
                'courses_id' => 92,
                'semesters_id' => 3,
                'major_id' => 8,
            ],
            // CY
            // CP422011 Introduction to Computer Networking
            [
                'section_num' => 1,
                'title' => 'กลุ่ม 1',
                'open_num' => 43,
                'enrolled_num' => 34,
                'available_num' => 9,
                'teachers_id' => 9,
                'courses_id' => 93,
                'semesters_id' => 3,
                'major_id' => 9,
            ],
            [
                'section_num' => 2,
                'title' => 'กลุ่ม 2',
                'open_num' => 43,
                'enrolled_num' => 42,
                'available_num' => 1,
                'teachers_id' => 9,
                'courses_id' => 101,
                'semesters_id' => 3,
                'major_id' => 10,
            ],
            // CP421025 Software Design and Analysis
            [
                'section_num' => 1,
                'title' => 'กลุ่ม 1',
                'open_num' => 90,
                'enrolled_num' => 76,
                'available_num' => 14,
                'teachers_id' => 31,
                'courses_id' => 94,
                'semesters_id' => 3,
                'major_id' => 9,
            ],
            // CP422022 Database Architecture Analysis and Design
            [
                'section_num' => 1,
                'title' => 'กลุ่ม 1',
                'open_num' => 43,
                'enrolled_num' => 33,
                'available_num' => 10,
                'teachers_id' => 29,
                'courses_id' => 95,
                'semesters_id' => 3,
                'major_id' => 9,
            ],
            [
                'section_num' => 2,
                'title' => 'กลุ่ม 2',
                'open_num' => 43,
                'enrolled_num' => 43,
                'available_num' => 0,
                'teachers_id' => 29,
                'courses_id' => 103,
                'semesters_id' => 3,
                'major_id' => 10,
            ],
            // CP422001 Cybersecurity Law and Ethic
            [
                'section_num' => 1,
                'title' => 'กลุ่ม 1',
                'open_num' => 88,
                'enrolled_num' => 87,
                'available_num' => 1,
                'teachers_id' => 5,
                'courses_id' => 96,
                'semesters_id' => 3,
                'major_id' => 9,
            ],
            [
                'section_num' => 2,
                'title' => 'กลุ่ม 2',
                'open_num' => 63,
                'enrolled_num' => 62,
                'available_num' => 1,
                'teachers_id' => 5,
                'courses_id' => 104,
                'semesters_id' => 3,
                'major_id' => 10,
            ],
            // CP422052 Introduction to Operating System
            [
                'section_num' => 1,
                'title' => 'กลุ่ม 1',
                'open_num' => 43,
                'enrolled_num' => 33,
                'available_num' => 10,
                'teachers_id' => 5,
                'courses_id' => 97,
                'semesters_id' => 3,
                'major_id' => 9,
            ],
            [
                'section_num' => 2,
                'title' => 'กลุ่ม 2',
                'open_num' => 43,
                'enrolled_num' => 43,
                'available_num' => 0,
                'teachers_id' => 5,
                'courses_id' => 105,
                'semesters_id' => 3,
                'major_id' => 10,
            ],
            // CP421011 Inspiration in Cybersecurity Career
            [
                'section_num' => 1,
                'title' => 'กลุ่ม 1',
                'open_num' => 88,
                'enrolled_num' => 88,
                'available_num' => 0,
                'teachers_id' => 32,
                'courses_id' => 98,
                'semesters_id' => 3,
                'major_id' => 9,
            ],
            [
                'section_num' => 2,
                'title' => 'กลุ่ม 2',
                'open_num' => 63,
                'enrolled_num' => 62,
                'available_num' => 1,
                'teachers_id' => 32,
                'courses_id' => 106,
                'semesters_id' => 3,
                'major_id' => 10,
            ],
            // CP422021 Web and Mobile Application Architecture
            [
                'section_num' => 1,
                'title' => 'กลุ่ม 1',
                'open_num' => 43,
                'enrolled_num' => 42,
                'available_num' => 1,
                'teachers_id' => 32,
                'courses_id' => 99,
                'semesters_id' => 3,
                'major_id' => 9,
            ],
            [
                'section_num' => 2,
                'title' => 'กลุ่ม 2',
                'open_num' => 43,
                'enrolled_num' => 34,
                'available_num' => 9,
                'teachers_id' => 32,
                'courses_id' => 107,
                'semesters_id' => 3,
                'major_id' => 10,
            ],
            // CP421021 Structured Programming
            [
                'section_num' => 1,
                'title' => 'กลุ่ม 1',
                'open_num' => 44,
                'enrolled_num' => 44,
                'available_num' => 0,
                'teachers_id' => 35,
                'courses_id' => 100,
                'semesters_id' => 3,
                'major_id' => 9,
            ],
            [
                'section_num' => 2,
                'title' => 'กลุ่ม 2',
                'open_num' => 44,
                'enrolled_num' => 44,
                'available_num' => 0,
                'teachers_id' => 35,
                'courses_id' => 100,
                'semesters_id' => 3,
                'major_id' => 9,
            ],
            [
                'section_num' => 3,
                'title' => 'กลุ่ม 3',
                'open_num' => 63,
                'enrolled_num' => 61,
                'available_num' => 2,
                'teachers_id' => 35,
                'courses_id' => 108,
                'semesters_id' => 3,
                'major_id' => 10,
            ],

        ];

        foreach ($classes as $key => $value) {
            Classes::create($value);
        }
    }
}
