<?php

namespace Database\Seeders;

// use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use App\Models\User;
use Illuminate\Support\Facades\Hash;
use Illuminate\Database\QueryException;
use Illuminate\Support\Facades\DB;

class CreateUsersSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        
        $users = [
            [
                'prefix'=>null,
                "fname"=> "Admin",
                "lname"=> "Admin",
                'student_id'=>null,
                'email'=> 'admin@admin.com',
                'card_id'=>null,
                'phone'=>null,
                'type' => '1',
                'password' => bcrypt('1234'),
            ],  
            [
                'prefix'=>null,
                'fname'=> 'Sirapat',
                'lname'=>'Chiewchanwattana',
                'student_id'=>null,
                'email'=> 'sunkra@kku.ac.th',
                'card_id'=>null,
                'phone'=>null,
                'type' => '2',
                'password' => bcrypt('1234'),
            ],
            [
                'prefix'=>null,
                'fname'=> 'Sarun',
                'lname'=>'Apichontrakul',
                'student_id'=>null,
                'email'=> 'sarunap@kku.ac.th',
                'card_id'=>null,
                'phone'=>null,
                'type' => '2',
                'password' => bcrypt('1234'),
            ],
            [
                'prefix'=>null,
                'fname'=> 'Pusadee',
                'lname'=>'Seresangtakul',
                'student_id'=>null,
                'email'=> 'pusadee@kku.ac.th',
                'card_id'=>null,
                'phone'=>null,
                'type' => '2',
                'password' => bcrypt('1234'),
            ],
            [
                'prefix'=>null,
                'fname'=> 'Chitsutha',
                'lname'=>'Soomlek',
                'student_id'=>null,
                'email'=> 'chitsutha@kku.ac.th',
                'card_id'=>null,
                'phone'=>null,
                'type' => '2',
                'password' => bcrypt('1234'),
            ],
            [
                'prefix'=>null,
                'fname'=> 'Satit',
                'lname'=>'Kravenkit',
                'student_id'=>null,
                'email'=> 'satikr@kku.ac.th',
                'card_id'=>null,
                'phone'=>null,
                'type' => '2',
                'password' => bcrypt('1234'),
            ],
            [
                'prefix'=>null,
                'fname'=> 'Nagon',
                'lname'=>'Watanakij',
                'student_id'=>null,
                'email'=> 'nagon@kku.ac.th',
                'card_id'=>null,
                'phone'=>null,
                'type' => '2',
                'password' => bcrypt('1234'),
            ],
            [
                'prefix'=>null,
                'fname'=> 'Chanon',
                'lname'=>'Dechsupa',
                'student_id'=>null,
                'email'=> 'chanode@kku.ac.th',
                'card_id'=>null,
                'phone'=>null,
                'type' => '2',
                'password' => bcrypt('1234'),
            ],
            [
                'prefix'=>null,
                'fname'=> 'Sartra',
                'lname'=>'Wongthanavasu',
                'student_id'=>null,
                'email'=> 'wongsar@kku.ac.th',
                'card_id'=>null,
                'phone'=>null,
                'type' => '2',
                'password' => bcrypt('1234'),
            ],
            [
                'prefix'=>null,
                'fname'=> 'Chakchai',
                'lname'=>'So-In',
                'student_id'=>null,
                'email'=> 'chakso@kku.ac.th',
                'card_id'=>null,
                'phone'=>null,
                'type' => '2',
                'password' => bcrypt('1234'),
            ],
            [
                'prefix'=>null,
                'fname'=> 'Punyaphol',
                'lname'=>'Horata',
                'student_id'=>null,
                'email'=> 'punhor1@kku.ac.th',
                'card_id'=>null,
                'phone'=>null,
                'type' => '2',
                'password' => bcrypt('1234'),
            ],
            [
                'prefix'=>null,
                'fname'=> 'Ngamnij',
                'lname'=>'Arch-int',
                'student_id'=>null,
                'email'=> 'ngamnij@kku.ac.th',
                'card_id'=>null,
                'phone'=>null,
                'type' => '2',
                'password' => bcrypt('1234'),
            ],
            [
                'prefix'=>null,
                'fname'=> 'Urachart',
                'lname'=>'Kokaew',
                'student_id'=>null,
                'email'=> 'urachart@kku.ac.th',
                'card_id'=>null,
                'phone'=>null,
                'type' => '2',
                'password' => bcrypt('1234'),
            ],
            [
                'prefix'=>null,
                'fname'=> 'Chaiyapon',
                'lname'=>'Keeratikasikorn',
                'student_id'=>null,
                'email'=> 'chaiyapon@kku.ac.th',
                'card_id'=>null,
                'phone'=>null,
                'type' => '2',
                'password' => bcrypt('1234'),
            ],
            [
                'prefix'=>null,
                'fname'=> 'Wararat',
                'lname'=>'Songpan',
                'student_id'=>null,
                'email'=> 'wararat@kku.ac.th',
                'card_id'=>null,
                'phone'=>null,
                'type' => '2',
                'password' => bcrypt('1234'),
            ],
            [
                'prefix'=>null,
                'fname'=> 'Sunti',
                'lname'=>'Tintanai',
                'student_id'=>null,
                'email'=> 'sunti@kku.ac.th',
                'card_id'=>null,
                'phone'=>null,
                'type' => '2',
                'password' => bcrypt('1234'),
            ],
            [
                'prefix'=>null,
                'fname'=> 'Khamron',
                'lname'=>'Sunat',
                'student_id'=>null,
                'email'=> 'skhamron@kku.ac.th',
                'card_id'=>null,
                'phone'=>null,
                'type' => '2',
                'password' => bcrypt('1234'),
            ],
            [
                'prefix'=>null,
                'fname'=> 'Pipat',
                'lname'=>'Reungsang',
                'student_id'=>null,
                'email'=> 'reungsang@kku.ac.th',
                'card_id'=>null,
                'phone'=>null,
                'type' => '2',
                'password' => bcrypt('1234'),
            ],
            [
                'prefix'=>null,
                'fname'=> 'Boonsup',
                'lname'=>'Waikham',
                'student_id'=>null,
                'email'=> 'boonsup@kku.ac.th',
                'card_id'=>null,
                'phone'=>null,
                'type' => '2',
                'password' => bcrypt('1234'),
            ],
            [
                'prefix'=>null,
                'fname'=> 'Wachirawut',
                'lname'=>'Tamviset',
                'student_id'=>null,
                'email'=> 'twachi@kku.ac.th',
                'card_id'=>null,
                'phone'=>null,
                'type' => '2',
                'password' => bcrypt('1234'),
            ],
            [
                'prefix'=>null,
                'fname'=> 'Urawan',
                'lname'=>'Chanket',
                'student_id'=>null,
                'email'=> 'curawa@kku.ac.th',
                'card_id'=>null,
                'phone'=>null,
                'type' => '2',
                'password' => bcrypt('1234'),
            ],
            [
                'prefix'=>null,
                'fname'=> 'Sumonta',
                'lname'=>'Kasemvilas',
                'student_id'=>null,
                'email'=> 'sumkas@kku.ac.th',
                'card_id'=>null,
                'phone'=>null,
                'type' => '2',
                'password' => bcrypt('1234'),
            ],
            [
                'prefix'=>null,
                'fname'=> 'Saiyan',
                'lname'=>'Saiyod',
                'student_id'=>null,
                'email'=> 'saiyan@kku.ac.th',
                'card_id'=>null,
                'phone'=>null,
                'type' => '2',
                'password' => bcrypt('1234'),
            ],
            [
                'prefix'=>null,
                'fname'=> 'Paweena',
                'lname'=>'Wanchai',
                'student_id'=>null,
                'email'=> 'wpaweena@kku.ac.th',
                'card_id'=>null,
                'phone'=>null,
                'type' => '2',
                'password' => bcrypt('1234'),
            ],
            [
                'prefix'=>null,
                'fname'=> 'Silada',
                'lname'=>'Intarasothonchun',
                'student_id'=>null,
                'email'=> 'silain@kku.ac.th',
                'card_id'=>null,
                'phone'=>null,
                'type' => '2',
                'password' => bcrypt('1234'),
            ],
            [
                'prefix'=>null,
                'fname'=> 'Monlica',
                'lname'=>'Wattana',
                'student_id'=>null,
                'email'=> 'monlwa@kku.ac.th',
                'card_id'=>null,
                'phone'=>null,
                'type' => '2',
                'password' => bcrypt('1234'),
            ],
            [
                'prefix'=>null,
                'fname'=> 'Praisan',
                'lname'=>'Padungweang',
                'student_id'=>null,
                'email'=> 'praipa@kku.ac.th',
                'card_id'=>null,
                'phone'=>null,
                'type' => '2',
                'password' => bcrypt('1234'),
            ],
            [
                'prefix'=>null,
                'fname'=> 'Sakpod',
                'lname'=>'Tongleamnak',
                'student_id'=>null,
                'email'=> 'sakpod@kku.ac.th',
                'card_id'=>null,
                'phone'=>null,
                'type' => '2',
                'password' => bcrypt('1234'),
            ],
            [
                'prefix'=>null,
                'fname'=> 'Pobporn',
                'lname'=>'Danvirutai',
                'student_id'=>null,
                'email'=> 'pobda@kku.ac.th',
                'card_id'=>null,
                'phone'=>null,
                'type' => '2',
                'password' => bcrypt('1234'),
            ],
            [
                'prefix'=>null,
                'fname'=> 'Pongsathon',
                'lname'=>'Janyoi',
                'student_id'=>null,
                'email'=> 'pongsathon@kku.ac.th',
                'card_id'=>null,
                'phone'=>null,
                'type' => '2',
                'password' => bcrypt('1234'),
            ],
            [
                'prefix'=>null,
                'fname'=> 'Warunya',
                'lname'=>'Wunnasri',
                'student_id'=>null,
                'email'=> 'waruwu@kku.ac.th',
                'card_id'=>null,
                'phone'=>null,
                'type' => '2',
                'password' => bcrypt('1234'),
            ],
            [
                'prefix'=>null,
                'fname'=> 'Jakkrit',
                'lname'=>'Kaewyotha',
                'student_id'=>null,
                'email'=> 'jakkritk@kku.ac.th',
                'card_id'=>null,
                'phone'=>null,
                'type' => '2',
                'password' => bcrypt('1234'),
            ],
            [
                'prefix'=>null,
                'fname'=> 'Phet',
                'lname'=>'Aimtongkham',
                'student_id'=>null,
                'email'=> 'phetim@kku.ac.th',
                'card_id'=>null,
                'phone'=>null,
                'type' => '2',
                'password' => bcrypt('1234'),
            ],
            [
                'prefix'=>null,
                'fname'=> 'Arfat Ahmad',
                'lname'=>'Khan',
                'student_id'=>null,
                'email'=> 'arfatkhan@kku.ac.th',
                'card_id'=>null,
                'phone'=>null,
                'type' => '2',
                'password' => bcrypt('1234'),
            ],
            [
                'prefix'=>null,
                'fname'=> 'Wasana',
                'lname'=>'Putklang',
                'student_id'=>null,
                'email'=> 'putklang_w@kku.ac.th',
                'card_id'=>null,
                'phone'=>null,
                'type' => '2',
                'password' => bcrypt('1234'),
            ],
            [
                'prefix'=>null,
                'fname'=> 'Isoon',
                'lname'=>'Kanjanasurat',
                'student_id'=>null,
                'email'=> 'isoonkan@kku.ac.th',
                'card_id'=>null,
                'phone'=>null,
                'type' => '2',
                'password' => bcrypt('1234'),
            ],
            [
                'prefix'=>null,
                'fname'=> 'Pakarat',
                'lname'=>'Musikawan',
                'student_id'=>null,
                'email'=> 'pakamu@kku.ac.th',
                'card_id'=>null,
                'phone'=>null,
                'type' => '2',
                'password' => bcrypt('1234'),
            ],
            [
                'prefix'=>null,
                'fname'=> 'Yanika',
                'lname'=>'Kongsorot',
                'student_id'=>null,
                'email'=> 'yaniko@kku.ac.th',
                'card_id'=>null,
                'phone'=>null,
                'type' => '2',
                'password' => bcrypt('1234'),
            ],
            [
                'prefix'=>null,
                'fname'=> 'Thanaphon',
                'lname'=>'Tangchoopong',
                'student_id'=>null,
                'email'=> 'thanaphon@kku.ac.th',
                'card_id'=>null,
                'phone'=>null,
                'type' => '2',
                'password' => bcrypt('1234'),
            ],
            [
                'prefix'=>'นาย',
                'fname'=> 'ชาคริต',
                'lname'=> 'ปรากฎ',
                'student_id'=>'643021316-6',
                'email'=> 'chakit.p@kkumail.com',
                'card_id'=>'1199654564565',
                'phone'=>'0812345678',
                'type' => '0',
                'password' => bcrypt('1234'),
            ],
        ];

        foreach ($users as $key => $value) {
            User::create($value);
        }

        // foreach ($users as $user) {
        //     DB::table('users')->insert($user);
        // }
    }
}
