<?php

namespace Database\Seeders;

// use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use App\Models\User;
use Illuminate\Support\Facades\Hash;
use Illuminate\Database\QueryException;
use Illuminate\Support\Facades\DB;

class CreateUsersSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $users = [
            [
                'prefix' => null,
                "name" => "Admin",
                'student_id' => null,
                'email' => 'admin@admin.com',
                'card_id' => null,
                'phone' => null,
                'type' => '1',
                'password' => bcrypt('1234'),
            ],

            [
                'prefix' => null,
                'name' => 'คำรณ สุนัติ',
                'student_id' => null,
                'email' => 'skhamron@kku.ac.th',
                'card_id' => null,
                'phone' => null,
                'type' => '2',
                'password' => bcrypt('1234'),
            ],
            [
                'prefix' => null,
                'name' => 'พุธษดี ศิริแสงตระกูล',
                'student_id' => null,
                'email' => 'pusadee@kku.ac.th',
                'card_id' => null,
                'phone' => null,
                'type' => '2',
                'password' => bcrypt('1234'),
            ],
            [
                'prefix' => null,
                'name' => 'สิรภัทร เชี่ยวชาญวัฒนา',
                'student_id' => null,
                'email' => 'sunkra@kku.ac.th',
                'card_id' => null,
                'phone' => null,
                'type' => '2',
                'password' => bcrypt('1234'),
            ],
            [
                'prefix' => null,
                'name' => 'ชิตสุธา สุ่มเล็ก',
                'student_id' => null,
                'email' => 'chitsutha@kku.ac.th',
                'card_id' => null,
                'phone' => null,
                'type' => '2',
                'password' => bcrypt('1234'),
            ],
            [
                'prefix' => null,
                'name' => 'ศาสตรา วงศ์ธนวสุ',
                'student_id' => null,
                'email' => 'wongsar@kku.ac.th',
                'card_id' => null,
                'phone' => null,
                'type' => '2',
                'password' => bcrypt('1234'),
            ],
            [
                'prefix' => null,
                'name' => 'สมจิตร อาจอินทร์',
                'student_id' => null,
                'email' => 'somjitr@kku.ac.th',
                'card_id' => null,
                'phone' => null,
                'type' => '2',
                'password' => bcrypt('1234'),
            ],
            [
                'prefix' => null,
                'name' => 'อภิศักดิ์ พัฒนจักร',
                'student_id' => null,
                'email' => 'apisak@kku.ac.th',
                'card_id' => null,
                'phone' => null,
                'type' => '2',
                'password' => bcrypt('1234'),
            ],
            [
                'prefix' => null,
                'name' => 'งามนิจ อาจอินทร์',
                'student_id' => null,
                'email' => 'ngamnij@kku.ac.th',
                'card_id' => null,
                'phone' => null,
                'type' => '2',
                'password' => bcrypt('1234'),
            ],
            [
                'prefix' => null,
                'name' => 'ปวีณา วันชัย',
                'student_id' => null,
                'email' => 'wpaweena@kku.ac.th',
                'card_id' => null,
                'phone' => null,
                'type' => '2',
                'password' => bcrypt('1234'),
            ],
            [
                'prefix' => null,
                'name' => 'สายยัญ สายยศ',
                'student_id' => null,
                'email' => 'saiyan@kku.ac.th',
                'card_id' => null,
                'phone' => null,
                'type' => '2',
                'password' => bcrypt('1234'),
            ],
            [
                'prefix' => null,
                'name' => 'ปัญญาพล หอระตะ',
                'student_id' => null,
                'email' => 'punhor1@kku.ac.th',
                'card_id' => null,
                'phone' => null,
                'type' => '2',
                'password' => bcrypt('1234'),
            ],
            [
                'prefix' => null,
                'name' => 'ธีระยุทธ ทองเครือ',
                'student_id' => null,
                'email' => 'theerayut@kku.ac.th',
                'card_id' => null,
                'phone' => null,
                'type' => '2',
                'password' => bcrypt('1234'),
            ],
            [
                'prefix' => null,
                'name' => 'ธนพล ตั้งชูพงศ์',
                'student_id' => null,
                'email' => 'thanaphon@kku.ac.th',
                'card_id' => null,
                'phone' => null,
                'type' => '2',
                'password' => bcrypt('1234'),
            ],
            [
                'prefix' => null,
                'name' => 'บุญทรัพย์ ไวคำ',
                'student_id' => null,
                'email' => 'boonsup@kku.ac.th',
                'card_id' => null,
                'phone' => null,
                'type' => '2',
                'password' => bcrypt('1234'),
            ],
            [
                'prefix' => null,
                'name' => 'อุรฉัตร โคแก้ว',
                'student_id' => null,
                'email' => 'urachart@kku.ac.th',
                'card_id' => null,
                'phone' => null,
                'type' => '2',
                'password' => bcrypt('1234'),
            ],
            [
                'prefix' => null,
                'name' => 'สิลดา อินทรโสธรฉันท์',
                'student_id' => null,
                'email' => 'silain@kku.ac.th',
                'card_id' => null,
                'phone' => null,
                'type' => '2',
                'password' => bcrypt('1234'),
            ],
            [
                'prefix' => null,
                'name' => 'วรัญญา วรรณศรี',
                'student_id' => null,
                'email' => 'waruwu@kku.ac.th',
                'card_id' => null,
                'phone' => null,
                'type' => '2',
                'password' => bcrypt('1234'),
            ],
            [
                'prefix' => null,
                'name' => 'สันติ ทินตะนัย',
                'student_id' => null,
                'email' => 'sunti@kku.ac.th',
                'card_id' => null,
                'phone' => null,
                'type' => '2',
                'password' => bcrypt('1234'),
            ],
            [
                'prefix' => null,
                'name' => 'จักรชัย โสอินทร์',
                'student_id' => null,
                'email' => 'chakso@kku.ac.th',
                'card_id' => null,
                'phone' => null,
                'type' => '2',
                'password' => bcrypt('1234'),
            ],
            [
                'prefix' => null,
                'name' => 'สุมณฑา เกษมวิลาศ',
                'student_id' => null,
                'email' => 'sumkas@kku.ac.th',
                'card_id' => null,
                'phone' => null,
                'type' => '2',
                'password' => bcrypt('1234'),
            ],
            [
                'prefix' => null,
                'name' => 'วรารัตน์ สงฆ์แป้น',
                'student_id' => null,
                'email' => 'wararat@kku.ac.th',
                'card_id' => null,
                'phone' => null,
                'type' => '2',
                'password' => bcrypt('1234'),
            ],
            [
                'prefix' => null,
                'name' => 'นันท์นภัส เบญจมาศ',
                'student_id' => null,
                'email' => 'nannapas@kku.ac.th',
                'card_id' => null,
                'phone' => null,
                'type' => '2',
                'password' => bcrypt('1234'),
            ],
            [
                'prefix' => null,
                'name' => 'มัลลิกา วัฒนะ',
                'student_id' => null,
                'email' => 'monlwa@kku.ac.th',
                'card_id' => null,
                'phone' => null,
                'type' => '2',
                'password' => bcrypt('1234'),
            ],
            [
                'prefix' => null,
                'name' => 'วชิราวุธ ธรรมวิเศษ',
                'student_id' => null,
                'email' => 'twachi@kku.ac.th',
                'card_id' => null,
                'phone' => null,
                'type' => '2',
                'password' => bcrypt('1234'),
            ],
            [
                'prefix' => null,
                'name' => 'พิพัธน์ เรืองแสง',
                'student_id' => null,
                'email' => 'reungsang@kku.ac.th',
                'card_id' => null,
                'phone' => null,
                'type' => '2',
                'password' => bcrypt('1234'),
            ],
            [
                'prefix' => null,
                'name' => 'ชัยพล กีรติกสิกร',
                'student_id' => null,
                'email' => 'chaiyapon@kku.ac.th',
                'card_id' => null,
                'phone' => null,
                'type' => '2',
                'password' => bcrypt('1234'),
            ],
            [
                'prefix' => null,
                'name' => 'ณกร วัฒนกิจ',
                'student_id' => null,
                'email' => 'nagon@kku.ac.th',
                'card_id' => null,
                'phone' => null,
                'type' => '2',
                'password' => bcrypt('1234'),
            ],
            [
                'prefix' => null,
                'name' => 'อุราวรรณ จันทร์เกษ',
                'student_id' => null,
                'email' => 'curawa@kku.ac.th',
                'card_id' => null,
                'phone' => null,
                'type' => '2',
                'password' => bcrypt('1234'),
            ],
            [
                'prefix' => null,
                'name' => 'ศรัณย์ อภิชนตระกูล',
                'student_id' => null,
                'email' => 'sarunap@kku.ac.th',
                'card_id' => null,
                'phone' => null,
                'type' => '2',
                'password' => bcrypt('1234'),
            ],
            [
                'prefix' => null,
                'name' => 'รัศมี สุวรรณวีระกำธร',
                'student_id' => null,
                'email' => 'rasamee@kku.ac.th',
                'card_id' => null,
                'phone' => null,
                'type' => '2',
                'password' => bcrypt('1234'),
            ],
            [
                'prefix' => null,
                'name' => 'รภัสสิทธิ์ ชินภัทรจีรัสถ์',
                'student_id' => null,
                'email' => 'rapassit@kku.ac.th',
                'card_id' => null,
                'phone' => null,
                'type' => '2',
                'password' => bcrypt('1234'),
            ],
            [
                'prefix' => null,
                'name' => 'ศักดิ์พจน์ ทองเลี่ยมนาค',
                'student_id' => null,
                'email' => 'sakpod@kku.ac.th',
                'card_id' => null,
                'phone' => null,
                'type' => '2',
                'password' => bcrypt('1234'),
            ],
            [
                'prefix' => null,
                'name' => 'เพชร อิ่มทองคำ',
                'student_id' => null,
                'email' => 'phetim@kku.ac.th',
                'card_id' => null,
                'phone' => null,
                'type' => '2',
                'password' => bcrypt('1234'),
            ],
            [
                'prefix' => null,
                'name' => 'ชานนท์ เดชสุภา',
                'student_id' => null,
                'email' => 'chanode@kku.ac.th',
                'card_id' => null,
                'phone' => null,
                'type' => '2',
                'password' => bcrypt('1234'),
            ],
            [
                'prefix' => null,
                'name' => 'ไพรสันต์ ผดุงเวียง',
                'student_id' => null,
                'email' => 'praipa@kku.ac.th',
                'card_id' => null,
                'phone' => null,
                'type' => '2',
                'password' => bcrypt('1234'),
            ],
            [
                'prefix' => null,
                'name' => 'ญานิกา คงโสรส',
                'student_id' => null,
                'email' => 'yaniko@kku.ac.th',
                'card_id' => null,
                'phone' => null,
                'type' => '2',
                'password' => bcrypt('1234'),
            ],
            [
                'prefix' => null,
                'name' => 'ภัคราช มุสิกะวัน',
                'student_id' => null,
                'email' => 'pakamu@kku.ac.th',
                'card_id' => null,
                'phone' => null,
                'type' => '2',
                'password' => bcrypt('1234'),
            ],
            [
                'prefix' => null,
                'name' => 'วาสนา พุฒกลาง',
                'student_id' => null,
                'email' => 'putklang_w@kku.ac.th',
                'card_id' => null,
                'phone' => null,
                'type' => '2',
                'password' => bcrypt('1234'),
            ],
            [
                'prefix' => null,
                'name' => 'Arfat Ahmad Khan',
                'student_id' => null,
                'email' => 'arfatkhan@kku.ac.th',
                'card_id' => null,
                'phone' => null,
                'type' => '2',
                'password' => bcrypt('1234'),
            ],
            [
                'prefix' => null,
                'name' => 'จักรกฤษณ์ แก้วโยธา',
                'student_id' => null,
                'email' => 'jakkritk@kku.ac.th',
                'card_id' => null,
                'phone' => null,
                'type' => '2',
                'password' => bcrypt('1234'),
            ],
            [
                'prefix' => null,
                'name' => 'พงษ์ศธร จันทร์ยอย',
                'student_id' => null,
                'email' => 'pongsathon@kku.ac.th',
                'card_id' => null,
                'phone' => null,
                'type' => '2',
                'password' => bcrypt('1234'),
            ],
            [
                'prefix' => null,
                'name' => 'ไอศูรย์ กาญจนสุรัตน์',
                'student_id' => null,
                'email' => 'isoonkan@kku.ac.th',
                'card_id' => null,
                'phone' => null,
                'type' => '2',
                'password' => bcrypt('1234'),
            ],
            [
                'prefix' => null,
                'name' => 'สาธิต กระเวนกิจ',
                'student_id' => null,
                'email' => 'satikr@kku.ac.th',
                'card_id' => null,
                'phone' => null,
                'type' => '2',
                'password' => bcrypt('1234'),
            ],
            [
                'prefix' => null,
                'name' => 'สุมาลี ชัยเจริญ',
                'student_id' => null,
                'email' => 'sumalee@kku.ac.th',
                'card_id' => null,
                'phone' => null,
                'type' => '2',
                'password' => bcrypt('1234'),
            ],
            [
                'prefix' => null,
                'name' => 'จารุณี ซามาตย์',
                'student_id' => null,
                'email' => 'scharu@kku.ac.th',
                'card_id' => null,
                'phone' => null,
                'type' => '2',
                'password' => bcrypt('1234'),
            ],
            [
                'prefix' => null,
                'name' => 'อนุชา โสมาบุตร',
                'student_id' => null,
                'email' => 'sanucha@kku.ac.th',
                'card_id' => null,
                'phone' => null,
                'type' => '2',
                'password' => bcrypt('1234'),
            ],
            [
                'prefix' => null,
                'name' => 'พบพร ด่านวิรุทัย',
                'student_id' => null,
                'email' => 'pobda@kku.ac.th',
                'card_id' => null,
                'phone' => null,
                'type' => '2',
                'password' => bcrypt('1234'),
            ],
            [
                'prefix' => null,
                'name' => 'นายโรจนวรรณ หาดี',
                'student_id' => null,
                'email' => 'rojanha@kku.ac.th',
                'card_id' => null,
                'phone' => null,
                'type' => '2',
                'password' => bcrypt('1234'),
            ],
            [
                'prefix' => 'นาย',
                'name' => 'ชาคริต ปรากฎ',
                'student_id' => '643021316-6',
                'email' => 'chakit.p@kkumail.com',
                'card_id' => '1199654564565',
                'phone' => '0812345678',
                'type' => '0',
                'password' => bcrypt('1234'),
            ],
        ];

        foreach ($users as $key => $value) {
            User::create($value);
        }
    }
}
