<?php

namespace Database\Seeders;

// use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use App\Models\User;
use Illuminate\Support\Facades\Hash;
use Illuminate\Database\QueryException;
use Illuminate\Support\Facades\DB;

class CreateUsersSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        
        $users = [
            [
                'prefix'=>null,
                "name"=> "Admin",
                'student_id'=>null,
                'email'=> 'admin@admin.com',
                'card_id'=>null,
                'phone'=>null,
                'type' => '1',
                'password' => bcrypt('1234'),
            ],  
            [
                'prefix'=>null,
                'name'=> 'Sirapat Chiewchanwattana',
                'student_id'=>null,
                'email'=> 'sunkra@kku.ac.th',
                'card_id'=>null,
                'phone'=>null,
                'type' => '2',
                'password' => bcrypt('1234'),
            ],
            [
                'prefix'=>null,
                'name'=> 'Sarun Apichontrakul',
                'student_id'=>null,
                'email'=> 'sarunap@kku.ac.th',
                'card_id'=>null,
                'phone'=>null,
                'type' => '2',
                'password' => bcrypt('1234'),
            ],
            [
                'prefix'=>null,
                'name'=> 'Pusadee Seresangtakul',
                'student_id'=>null,
                'email'=> 'pusadee@kku.ac.th',
                'card_id'=>null,
                'phone'=>null,
                'type' => '2',
                'password' => bcrypt('1234'),
            ],
            [
                'prefix'=>null,
                'name'=> 'Chitsutha Soomlek',
                'student_id'=>null,
                'email'=> 'chitsutha@kku.ac.th',
                'card_id'=>null,
                'phone'=>null,
                'type' => '2',
                'password' => bcrypt('1234'),
            ],
            [
                'prefix'=>null,
                'name'=> 'Satit Kravenkit',
                'student_id'=>null,
                'email'=> 'satikr@kku.ac.th',
                'card_id'=>null,
                'phone'=>null,
                'type' => '2',
                'password' => bcrypt('1234'),
            ],
            [
                'prefix'=>null,
                'name'=> 'Nagon Watanakij',
                'student_id'=>null,
                'email'=> 'nagon@kku.ac.th',
                'card_id'=>null,
                'phone'=>null,
                'type' => '2',
                'password' => bcrypt('1234'),
            ],
            [
                'prefix'=>null,
                'name'=> 'Chanon Dechsupa',
                'student_id'=>null,
                'email'=> 'chanode@kku.ac.th',
                'card_id'=>null,
                'phone'=>null,
                'type' => '2',
                'password' => bcrypt('1234'),
            ],
            [
                'prefix'=>null,
                'name'=> 'Sartra Wongthanavasu',
                'student_id'=>null,
                'email'=> 'wongsar@kku.ac.th',
                'card_id'=>null,
                'phone'=>null,
                'type' => '2',
                'password' => bcrypt('1234'),
            ],
            [
                'prefix'=>null,
                'name'=> 'Chakchai So-In',
                'student_id'=>null,
                'email'=> 'chakso@kku.ac.th',
                'card_id'=>null,
                'phone'=>null,
                'type' => '2',
                'password' => bcrypt('1234'),
            ],
            [
                'prefix'=>null,
                'name'=> 'Punyaphol Horata',
                'student_id'=>null,
                'email'=> 'punhor1@kku.ac.th',
                'card_id'=>null,
                'phone'=>null,
                'type' => '2',
                'password' => bcrypt('1234'),
            ],
            [
                'prefix'=>null,
                'name'=> 'Ngamnij Arch-int',
                'student_id'=>null,
                'email'=> 'ngamnij@kku.ac.th',
                'card_id'=>null,
                'phone'=>null,
                'type' => '2',
                'password' => bcrypt('1234'),
            ],
            [
                'prefix'=>null,
                'name'=> 'Urachart Kokaew',
                'student_id'=>null,
                'email'=> 'urachart@kku.ac.th',
                'card_id'=>null,
                'phone'=>null,
                'type' => '2',
                'password' => bcrypt('1234'),
            ],
            [
                'prefix'=>null,
                'name'=> 'Chaiyapon Keeratikasikorn',
                'student_id'=>null,
                'email'=> 'chaiyapon@kku.ac.th',
                'card_id'=>null,
                'phone'=>null,
                'type' => '2',
                'password' => bcrypt('1234'),
            ],
            [
                'prefix'=>null,
                'name'=> 'Wararat Songpan',
                'student_id'=>null,
                'email'=> 'wararat@kku.ac.th',
                'card_id'=>null,
                'phone'=>null,
                'type' => '2',
                'password' => bcrypt('1234'),
            ],
            [
                'prefix'=>null,
                'name'=> 'Sunti Tintanai',
                'student_id'=>null,
                'email'=> 'sunti@kku.ac.th',
                'card_id'=>null,
                'phone'=>null,
                'type' => '2',
                'password' => bcrypt('1234'),
            ],
            [
                'prefix'=>null,
                'name'=> 'Khamron Sunat',
                'student_id'=>null,
                'email'=> 'skhamron@kku.ac.th',
                'card_id'=>null,
                'phone'=>null,
                'type' => '2',
                'password' => bcrypt('1234'),
            ],
            [
                'prefix'=>null,
                'name'=> 'Pipat Reungsang',
                'student_id'=>null,
                'email'=> 'reungsang@kku.ac.th',
                'card_id'=>null,
                'phone'=>null,
                'type' => '2',
                'password' => bcrypt('1234'),
            ],
            [
                'prefix'=>null,
                'name'=> 'Boonsup Waikham',
                'student_id'=>null,
                'email'=> 'boonsup@kku.ac.th',
                'card_id'=>null,
                'phone'=>null,
                'type' => '2',
                'password' => bcrypt('1234'),
            ],
            [
                'prefix'=>null,
                'name'=> 'Wachirawut Tamviset',
                'student_id'=>null,
                'email'=> 'twachi@kku.ac.th',
                'card_id'=>null,
                'phone'=>null,
                'type' => '2',
                'password' => bcrypt('1234'),
            ],
            [
                'prefix'=>null,
                'name'=> 'Urawan Chanket',
                'student_id'=>null,
                'email'=> 'curawa@kku.ac.th',
                'card_id'=>null,
                'phone'=>null,
                'type' => '2',
                'password' => bcrypt('1234'),
            ],
            [
                'prefix'=>null,
                'name'=> 'Sumonta Kasemvilas',
                'student_id'=>null,
                'email'=> 'sumkas@kku.ac.th',
                'card_id'=>null,
                'phone'=>null,
                'type' => '2',
                'password' => bcrypt('1234'),
            ],
            [
                'prefix'=>null,
                'name'=> 'Saiyan Saiyod',
                'student_id'=>null,
                'email'=> 'saiyan@kku.ac.th',
                'card_id'=>null,
                'phone'=>null,
                'type' => '2',
                'password' => bcrypt('1234'),
            ],
            [
                'prefix'=>null,
                'name'=> 'Paweena Wanchai',
                'student_id'=>null,
                'email'=> 'wpaweena@kku.ac.th',
                'card_id'=>null,
                'phone'=>null,
                'type' => '2',
                'password' => bcrypt('1234'),
            ],
            [
                'prefix'=>null,
                'name'=> 'Silada Intarasothonchun',
                'student_id'=>null,
                'email'=> 'silain@kku.ac.th',
                'card_id'=>null,
                'phone'=>null,
                'type' => '2',
                'password' => bcrypt('1234'),
            ],
            [
                'prefix'=>null,
                'name'=> 'Monlica Wattana',
                'student_id'=>null,
                'email'=> 'monlwa@kku.ac.th',
                'card_id'=>null,
                'phone'=>null,
                'type' => '2',
                'password' => bcrypt('1234'),
            ],
            [
                'prefix'=>null,
                'name'=> 'Praisan Padungweang',
                'student_id'=>null,
                'email'=> 'praipa@kku.ac.th',
                'card_id'=>null,
                'phone'=>null,
                'type' => '2',
                'password' => bcrypt('1234'),
            ],
            [
                'prefix'=>null,
                'name'=> 'Sakpod Tongleamnak',
                'student_id'=>null,
                'email'=> 'sakpod@kku.ac.th',
                'card_id'=>null,
                'phone'=>null,
                'type' => '2',
                'password' => bcrypt('1234'),
            ],
            [
                'prefix'=>null,
                'name'=> 'Pobporn Danvirutai',
                'student_id'=>null,
                'email'=> 'pobda@kku.ac.th',
                'card_id'=>null,
                'phone'=>null,
                'type' => '2',
                'password' => bcrypt('1234'),
            ],
            [
                'prefix'=>null,
                'name'=> 'Pongsathon Janyoi',
                'student_id'=>null,
                'email'=> 'pongsathon@kku.ac.th',
                'card_id'=>null,
                'phone'=>null,
                'type' => '2',
                'password' => bcrypt('1234'),
            ],
            [
                'prefix'=>null,
                'name'=> 'Warunya Wunnasri',
                'student_id'=>null,
                'email'=> 'waruwu@kku.ac.th',
                'card_id'=>null,
                'phone'=>null,
                'type' => '2',
                'password' => bcrypt('1234'),
            ],
            [
                'prefix'=>null,
                'name'=> 'Jakkrit Kaewyotha',
                'student_id'=>null,
                'email'=> 'jakkritk@kku.ac.th',
                'card_id'=>null,
                'phone'=>null,
                'type' => '2',
                'password' => bcrypt('1234'),
            ],
            [
                'prefix'=>null,
                'name'=> 'Phet Aimtongkham',
                'student_id'=>null,
                'email'=> 'phetim@kku.ac.th',
                'card_id'=>null,
                'phone'=>null,
                'type' => '2',
                'password' => bcrypt('1234'),
            ],
            [
                'prefix'=>null,
                'name'=> 'Arfat Ahmad Khan',
                'student_id'=>null,
                'email'=> 'arfatkhan@kku.ac.th',
                'card_id'=>null,
                'phone'=>null,
                'type' => '2',
                'password' => bcrypt('1234'),
            ],
            [
                'prefix'=>null,
                'name'=> 'Wasana Putklang',
                'student_id'=>null,
                'email'=> 'putklang_w@kku.ac.th',
                'card_id'=>null,
                'phone'=>null,
                'type' => '2',
                'password' => bcrypt('1234'),
            ],
            [
                'prefix'=>null,
                'name'=> 'Isoon Kanjanasurat',
                'student_id'=>null,
                'email'=> 'isoonkan@kku.ac.th',
                'card_id'=>null,
                'phone'=>null,
                'type' => '2',
                'password' => bcrypt('1234'),
            ],
            [
                'prefix'=>null,
                'name'=> 'Pakarat Musikawan',
                'student_id'=>null,
                'email'=> 'pakamu@kku.ac.th',
                'card_id'=>null,
                'phone'=>null,
                'type' => '2',
                'password' => bcrypt('1234'),
            ],
            [
                'prefix'=>null,
                'name'=> 'Yanika Kongsorot',
                'student_id'=>null,
                'email'=> 'yaniko@kku.ac.th',
                'card_id'=>null,
                'phone'=>null,
                'type' => '2',
                'password' => bcrypt('1234'),
            ],
            [
                'prefix'=>null,
                'name'=> 'Thanaphon Tangchoopong',
                'student_id'=>null,
                'email'=> 'thanaphon@kku.ac.th',
                'card_id'=>null,
                'phone'=>null,
                'type' => '2',
                'password' => bcrypt('1234'),
            ],
            [
                'prefix'=>'นาย',
                'name'=> 'ชาคริต ปรากฎ',
                'student_id'=>'643021316-6',
                'email'=> 'chakit.p@kkumail.com',
                'card_id'=>'1199654564565',
                'phone'=>'0812345678',
                'type' => '0',
                'password' => bcrypt('1234'),
            ],
        ];

        foreach ($users as $key => $value) {
            User::create($value);
        }
    }
}
